### ISSUE TITLE
Invalid column type

### ISSUE THREAD

**Issue by DVanderstoken** [awltech/sonar-data-migrator#1]
See stacktrace below :

`INFO  13-07 16:14:08,900 (SonarUserMigration.java:migrateUsers:42)  -start time Wed Jul 13 16:14:08 NCT 2016
INFO  13-07 16:14:09,403 (SonarUserMigration.java:migrateUsers:49)  -Does source DB supports retrival of auto generation of key? -true
INFO  13-07 16:14:09,408 (SonarUserMigration.java:migrateUsers:51)  -Does target DB supports retrival of auto generation of key? -true
INFO  13-07 16:14:09,409 (SonarUserMigration.java:migrateUsers:53)  -Auto generated key retrival is required for knowing newly generated id to be used as foreign key
INFO  13-07 16:14:09,409 (SonarUserMigration.java:migrateUsers:55)  -Preparing sql queries based on input
INFO  13-07 16:14:09,515 (SonarUserMigration.java:migrateUsers:67)  -Getting existing users from target DB
INFO  13-07 16:14:09,531 (SonarUserMigration.java:migrateUsers:78)  -Checking default group detail from target DB
INFO  13-07 16:14:09,535 (SonarUserMigration.java:migrateUsers:94)  -Comparing users from source DB and adding missing in target
ERROR 13-07 16:14:09,616 (SonarUserMigration.java:migrateUsers:177)  -Error while processing users
java.sql.SQLException: Type de colonne non valide: getTimestamp not implemented for class oracle.jdbc.driver.T4CNumberAccessor
    at oracle.jdbc.driver.Accessor.unimpl(Accessor.java:414)
    at oracle.jdbc.driver.Accessor.getTimestamp(Accessor.java:796)
    at oracle.jdbc.driver.OracleResultSetImpl.getTimestamp(OracleResultSetImpl.java:1422)
    at oracle.jdbc.driver.OracleResultSet.getTimestamp(OracleResultSet.java:516)
    at com.worldline.awltech.sonar.SonarUserMigration.migrateUsers(SonarUserMigration.java:118)
    at com.worldline.awltech.sonar.SonarMigrationUtil.executeMigration(SonarMigrationUtil.java:69)
    at com.worldline.awltech.sonar.SonarMigrationUtil.main(SonarMigrationUtil.java:51)
`

**Comment by alpesh-shah** [comment]
This migrator not tested with Oracle and not sure if it will perfectly work.  BTW were you able to solve the issue yourself looking at code?
