### ISSUE TITLE
ORA-00904 invalid identifier

### ISSUE THREAD

**Issue by DVanderstoken** [awltech/sonar-data-migrator#2]
See stacktrace below :

`INFO  13-07 16:42:46,834 (UpgradedSonarDataMigration.java:migrateData:269)  -############ Start working on Issues ######################
ERROR 13-07 16:42:46,896 (UpgradedSonarDataMigration.java:migrateData:480)  -Error while migrating data
java.sql.SQLSyntaxErrorException: ORA-00904: "ROOT_COMPONENT_ID" : identificateur non valide

```
at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:447)
at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:396)
at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:951)
at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:513)
at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:227)
at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:531)
at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:208)
at oracle.jdbc.driver.T4CPreparedStatement.executeForDescribe(T4CPreparedStatement.java:886)
at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:1175)
at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1296)
at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3613)
at oracle.jdbc.driver.OraclePreparedStatement.executeQuery(OraclePreparedStatement.java:3657)
at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeQuery(OraclePreparedStatementWrapper.java:1495)
at com.worldline.awltech.sonar.UpgradedSonarDataMigration.migrateData(UpgradedSonarDataMigration.java:309)
at com.worldline.awltech.sonar.SonarMigrationUtil.executeMigration(SonarMigrationUtil.java:75)
at com.worldline.awltech.sonar.SonarMigrationUtil.main(SonarMigrationUtil.java:51)
```

`

**Comment by alpesh-shah** [comment]
Are you sure you have correct source/target sonar version ? see wiki for details. I will not work for all sonar version.

Also this migrator not tested with Oracle and not sure if it will perfectly work.
